export interface CalendarEvent {
  name: string;
  month: number; // 1-12
  when: string; // how the date usually lands
  where: string;
  distance: string;
  discipline: "run" | "tri" | "bike" | "swim" | "trail";
  take: string; // our one-paragraph take
  races: string[]; // slugs of our reports
  offIsland?: boolean;
  series?: string;
}

/** The Oahu calendar the way we've actually raced it. Dates move year to year; check with the organizer before you plan a season around one. */
export const CALENDAR: CalendarEvent[] = [
  {
    name: "Bosetti Sunrise 10K",
    month: 1,
    when: "New Year's Day",
    where: "Hawaii Kai",
    distance: "10K",
    discipline: "run",
    take: "First bib of the year, before the resolutions have had a chance to fall apart. Flat enough to tell you exactly what December did to you.",
    races: ["bosetti-sunrise-10k-2023", "bosetti-sunrise-10k-2024", "bosetti-sunrise-10k-2025", "bosetti-sunrise-10k-2026"],
  },
  {
    name: "Akahai Half Marathon",
    month: 1,
    when: "January",
    where: "Oahu",
    distance: "13.1 mi",
    discipline: "run",
    take: "A January half is a weird thing to sign up for three weeks after a marathon. We did it anyway in 2023, mostly to keep the long run from disappearing over the holidays.",
    races: ["akahai-half-2023"],
  },
  {
    name: "Great Aloha Run",
    month: 2,
    when: "Presidents' Day",
    where: "Aloha Tower to Aloha Stadium",
    distance: "8.15 mi",
    discipline: "run",
    take: "For years this was the longest either of us had ever run. Huge crowd, real start-line energy, and a distance a beginner can finish without walking. It's where we'd tell anybody to start.",
    races: ["great-aloha-run-2023"],
  },
  {
    name: "Kailua 10-Miler",
    month: 2,
    when: "February",
    where: "Kailua",
    distance: "10 mi",
    discipline: "run",
    take: "Windward side, so the trades are either helping you or in your face depending on which way the course is pointed. You don't get to pick which half gets which.",
    races: ["kailua-10-miler-2023", "kailua-10-miler-2024", "kailua-10-miler-2025", "kailua-10-miler-2026"],
  },
  {
    name: "King's Runner 10K",
    month: 3,
    when: "Early March",
    where: "Honolulu",
    distance: "10K",
    discipline: "run",
    take: "Fast, flat, in town. Good for finding out what your legs are actually worth after a winter of slow miles.",
    races: ["kings-runner-10k-2023"],
  },
  {
    name: "Ku'ikahi 10K",
    month: 3,
    when: "March",
    where: "Oahu",
    distance: "10K",
    discipline: "run",
    take: "Michelle won her age group here in 2023. We bring this up a lot. We're going to keep bringing it up.",
    races: ["kuikahi-10k-2023"],
  },
  {
    name: "Windward Half Marathon",
    month: 3,
    when: "March",
    where: "Windward Oahu",
    distance: "13.1 mi",
    discipline: "run",
    take: "The pretty one. Also the humid one. Every half on this island turns into a heat race around mile nine, and this one has better scenery to distract you from that.",
    races: ["windward-half-2023", "windward-half-2024", "windward-half-2025"],
  },
  {
    name: "Hapalua Half Marathon",
    month: 4,
    when: "April",
    where: "Waikiki and Diamond Head",
    distance: "13.1 mi",
    discipline: "run",
    take: "Hawaii's half. Big, well run, and by April the start line's already warm enough to give you a preview of summer.",
    races: ["hapalua-half-2023", "hapalua-half-2024"],
  },
  {
    name: "Haleiwa Metric Century",
    month: 4,
    when: "April",
    where: "North Shore",
    distance: "100 km",
    discipline: "bike",
    take: "A long day on the North Shore with a bike club that's been at this for decades. Our first organized ride that felt long.",
    races: ["haleiwa-metric-century-2023"],
  },
  {
    name: "Honolulu Triathlon",
    month: 5,
    when: "May",
    where: "Ala Moana Beach Park",
    distance: "Olympic, plus shorter options",
    discipline: "tri",
    take: "We did this in 2014 without training and again in 2023 with it. Same course, different people. It's the only local Olympic-distance tri, so the whole spring points at it.",
    races: ["honolulu-triathlon-2014-and-again", "honolulu-triathlon-2024"],
  },
  {
    name: "Hibiscus Half Marathon",
    month: 5,
    when: "Memorial Day weekend",
    where: "Kapiolani Park and Diamond Head",
    distance: "13.1 mi",
    discipline: "run",
    take: "Our first half ever, in 2022. Michelle's PR, in 2023. Early start, Diamond Head loop, and if you're lucky a chicken at the top.",
    races: ["hibiscus-half-2022", "hibiscus-half-2023"],
  },
  {
    name: "IRONMAN 70.3 Hawaii (Honu)",
    month: 6,
    when: "Early June",
    where: "Waikoloa and Hawi, Big Island",
    distance: "1.2 / 56 / 13.1",
    discipline: "tri",
    take: "Not Oahu, but it's the one we fly for. Lava, wind on the road to Hawi, a run with zero shade. Jay's first 70.3, and the race where the distance itself became the point.",
    races: ["honu-70-3-2023", "honu-70-3-2024", "honu-70-3-2025", "honu-70-3-2026"],
    offIsland: true,
  },
  {
    name: "Cholo's Waimea Bay Swim",
    month: 6,
    when: "Late June",
    where: "Waimea Bay, North Shore",
    distance: "Ocean swim",
    discipline: "swim",
    take: "A North Shore ocean swim in the month the bay is flat. We did it once, three weeks after Honu, and it was the nicest 45 minutes of that June.",
    races: ["cholos-waimea-bay-2024"],
  },
  {
    name: "HURT Kaena Point Firecracker",
    month: 7,
    when: "Fourth of July weekend",
    where: "Kaena Point, west Oahu",
    distance: "10 mi trail",
    discipline: "trail",
    take: "Out and back on the dirt road to the tip of the island. No shade, no pavement, and a turnaround with whales in the winter and nothing but ocean in July.",
    races: ["kaena-point-10-mile-2024"],
  },
  {
    name: "Kailua Beach Shark Chase",
    month: 7,
    when: "Mid-July",
    where: "Kailua Beach",
    distance: "4.4 mi, on sand",
    discipline: "run",
    take: "A beach run in July. Nobody's pace means anything on sand, which is the whole point. Jay won his age group here in 2023 and we still don't know how.",
    races: ["kailua-shark-chase-2023", "kailua-shark-chase-2024"],
  },
  {
    name: "Lanikai 8K",
    month: 7,
    when: "July",
    where: "Lanikai and Kailua",
    distance: "8K",
    discipline: "run",
    take: "Short loop through the most photographed neighborhood on the island. Short doesn't mean easy in July.",
    races: ["lanikai-8k-2023"],
  },
  {
    name: "Na Wahine & Kane Sprint Triathlon",
    month: 7,
    when: "July",
    where: "Oahu",
    distance: "Sprint",
    discipline: "tri",
    take: "A sprint is where you learn transitions without them wrecking your whole day. We raced this one the summer Jay's new bike showed up.",
    races: ["na-wahine-kane-sprint-2023"],
  },
  {
    name: "Norman Tamanaha 15K",
    month: 8,
    when: "August",
    where: "Honolulu",
    distance: "15K",
    discipline: "run",
    take: "First race in the Marathon Readiness Series. If you're running the Honolulu Marathon, this is where the build starts having a bib on it.",
    races: ["norman-tamanaha-15k-2022", "norman-tamanaha-15k-2023", "norman-tamanaha-15k-2024"],
    series: "Marathon Readiness Series 1 of 5",
  },
  {
    name: "Dick Evans Memorial Road Race",
    month: 8,
    when: "August",
    where: "Around Oahu",
    distance: "112 mi",
    discipline: "bike",
    take: "A full lap of the island, the same ride the first Ironman used in February 1978. Same distance as an Ironman bike leg, in August, with real traffic. It taught us what 112 miles of eating looks like.",
    races: ["dick-evans-112-2023", "dick-evans-112-2024", "dick-evans-112-2025"],
  },
  {
    name: "Runner's HI 20K",
    month: 9,
    when: "September",
    where: "Honolulu",
    distance: "20K",
    discipline: "run",
    take: "Second in the series. The distance steps up and so does the heat, because September's the hottest stretch of the year here.",
    races: ["runners-hi-20k-2022", "runners-hi-20k-2023"],
    series: "Marathon Readiness Series 2 of 5",
  },
  {
    name: "Waikiki Roughwater Swim",
    month: 9,
    when: "Labor Day weekend",
    where: "Waikiki",
    distance: "2.4 mi",
    discipline: "swim",
    take: "The swim the first Ironman used in 1978, still run every September. The full 2.4 miles in the ocean with no bike waiting for you, which is a good way to find out whether the swim's the thing you should be worried about.",
    races: ["waikiki-2-4-mile-swim-2023"],
  },
  {
    name: "Honolulu Century Ride",
    month: 9,
    when: "Late September",
    where: "Kapiolani Park up the windward coast",
    distance: "25 to 100 mi",
    discipline: "bike",
    take: "Out and back along the windward coast with distance options, so it fits wherever you are in a season. The 100 is a long, hot, gorgeous day.",
    races: ["honolulu-century-ride-2023"],
  },
  {
    name: "Hybrid Design 25K",
    month: 9,
    when: "Late September or early October",
    where: "Honolulu",
    distance: "25K",
    discipline: "run",
    take: "Third in the series. Past half-marathon distance now, which is the whole idea.",
    races: ["hybrid-design-25k-2022", "hybrid-design-25k-2023"],
    series: "Marathon Readiness Series 3 of 5",
  },
  {
    name: "Tantalus 10-Mile Challenge",
    month: 10,
    when: "October",
    where: "Tantalus and Round Top",
    distance: "10 mi",
    discipline: "run",
    take: "Up the mountain road above town and back down. Not a PR course. A legs-and-honesty course.",
    races: ["tantalus-10-mile-2023"],
  },
  {
    name: "BOCA Hawaii 30K",
    month: 10,
    when: "October",
    where: "Honolulu",
    distance: "30K",
    discipline: "run",
    take: "Fourth in the series and the longest one. A 30K in October is as close as you'll get to a marathon dress rehearsal with a bib on.",
    races: ["boca-hawaii-30k-2022", "boca-hawaii-30k-2023"],
    series: "Marathon Readiness Series 4 of 5",
  },
  {
    name: "Val Nolasco Half Marathon",
    month: 11,
    when: "November",
    where: "Honolulu",
    distance: "13.1 mi",
    discipline: "run",
    take: "Last race in the series, a month out from the marathon. Run it as a check, not a race, if December's the goal.",
    races: ["val-nolasco-half-2022", "val-nolasco-half-2023", "val-nolasco-half-2024"],
    series: "Marathon Readiness Series 5 of 5",
  },
  {
    name: "Kaiwi Coast Fun Run",
    month: 11,
    when: "November",
    where: "Kaiwi coast, east Oahu",
    distance: "4 mi",
    discipline: "run",
    take: "The coast road between Sandy Beach and Makapuu. Fun run is the right name for it. Go for the view and the people.",
    races: ["kaiwi-coast-fun-run-2022", "kaiwi-coast-fun-run-2023", "kaiwi-coast-fun-run-2024", "kaiwi-coast-fun-run-2025"],
  },
  {
    name: "Turtle Bay Triathlon",
    month: 11,
    when: "November",
    where: "Turtle Bay, North Shore",
    distance: "Short course",
    discipline: "tri",
    take: "Late-season tri up on the North Shore, when the winter surf's already starting to show up. A good one to close out a tri year.",
    races: ["turtle-bay-triathlon-2023"],
  },
  {
    name: "Honolulu Marathon",
    month: 12,
    when: "Second Sunday of December",
    where: "Ala Moana to Kapiolani Park",
    distance: "26.2 mi",
    discipline: "run",
    take: "5 a.m. start, fireworks, Diamond Head twice, and no cutoff. The run leg of the first Ironman in 1978, and the reason the whole Oahu running calendar is shaped the way it is. Jay's 50th birthday race.",
    races: ["honolulu-marathon-for-fifty", "honolulu-marathon-2023", "honolulu-marathon-2024", "honolulu-marathon-2025"],
  },
];
