export interface CalendarEvent {
  name: string;
  month: number; // 1-12
  when: string; // how the date usually lands
  where: string;
  distance: string;
  discipline: "run" | "tri" | "bike" | "swim" | "trail";
  take: string; // our one-paragraph take
  races: string[]; // slugs of our reports
  offIsland?: boolean;
  series?: string;
}

/** The Oahu calendar as we have actually raced it. Dates drift year to year; confirm with the organizer before you plan a season around one. */
export const CALENDAR: CalendarEvent[] = [
  {
    name: "Bosetti Sunrise 10K",
    month: 1,
    when: "New Year's Day",
    where: "Hawaii Kai",
    distance: "10K",
    discipline: "run",
    take: "The first bib of the year, before the resolutions have had time to fail. Flat enough to be honest about where December left you.",
    races: ["bosetti-sunrise-10k-2024"],
  },
  {
    name: "Akahai Half Marathon",
    month: 1,
    when: "January",
    where: "Oahu",
    distance: "13.1 mi",
    discipline: "run",
    take: "A January half is a strange thing to sign up for three weeks after a marathon. We did it anyway in 2023. It kept the long run alive through the holidays.",
    races: ["akahai-half-2023"],
  },
  {
    name: "Great Aloha Run",
    month: 2,
    when: "Presidents' Day",
    where: "Aloha Tower to Aloha Stadium",
    distance: "8.15 mi",
    discipline: "run",
    take: "For years this was the longest thing either of us had run. Huge field, a real start line feeling, and a distance that lets a beginner finish upright.",
    races: ["great-aloha-run-2023"],
  },
  {
    name: "Kailua 10-Miler",
    month: 2,
    when: "February",
    where: "Kailua",
    distance: "10 mi",
    discipline: "run",
    take: "Windward side, which means the trade winds are either your friend or a wall depending on the direction of the leg you are on.",
    races: ["kailua-10-miler-2023"],
  },
  {
    name: "King's Runner 10K",
    month: 3,
    when: "Early March",
    where: "Honolulu",
    distance: "10K",
    discipline: "run",
    take: "A fast, flat town 10K. Good for finding out what your legs are actually worth after a winter of long slow miles.",
    races: ["kings-runner-10k-2023"],
  },
  {
    name: "Ku'ikahi 10K",
    month: 3,
    when: "March",
    where: "Oahu",
    distance: "10K",
    discipline: "run",
    take: "The race where Michelle won her age group in 2023. We mention this a lot. We will keep mentioning it.",
    races: ["kuikahi-10k-2023"],
  },
  {
    name: "Windward Half Marathon",
    month: 3,
    when: "March",
    where: "Windward Oahu",
    distance: "13.1 mi",
    discipline: "run",
    take: "The pretty one. Also the humid one. Every half on this island is a heat race by mile nine.",
    races: ["windward-half-2023"],
  },
  {
    name: "Hapalua Half Marathon",
    month: 4,
    when: "April",
    where: "Waikiki and Diamond Head",
    distance: "13.1 mi",
    discipline: "run",
    take: "Hawaii's half. Big, well-run, and by April it is warm enough at the start to tell you what summer will feel like.",
    races: ["hapalua-half-2023"],
  },
  {
    name: "Haleiwa Metric Century",
    month: 4,
    when: "April",
    where: "North Shore",
    distance: "100 km",
    discipline: "bike",
    take: "A long day on the North Shore with a bike club that has been doing this for decades. Our first organized ride that felt long.",
    races: ["haleiwa-metric-century-2023"],
  },
  {
    name: "Honolulu Triathlon",
    month: 5,
    when: "May",
    where: "Ala Moana Beach Park",
    distance: "Olympic, plus shorter options",
    discipline: "tri",
    take: "The race we did in 2014 without training and again in 2023 with it. Same course. Different people. The only local Olympic-distance tri, so it anchors the spring.",
    races: ["honolulu-triathlon-2014-and-again"],
  },
  {
    name: "Hibiscus Half Marathon",
    month: 5,
    when: "Memorial Day weekend",
    where: "Kapiolani Park and Diamond Head",
    distance: "13.1 mi",
    discipline: "run",
    take: "Our first half ever, in 2022. Michelle's PR, in 2023. Early start, Diamond Head loop, and a chicken at the top if you are lucky.",
    races: ["hibiscus-half-2022", "hibiscus-half-2023"],
  },
  {
    name: "IRONMAN 70.3 Hawaii (Honu)",
    month: 6,
    when: "Early June",
    where: "Waikoloa and Hawi, Big Island",
    distance: "1.2 / 56 / 13.1",
    discipline: "tri",
    take: "Not Oahu, but the one we fly for. Lava, wind on the road to Hawi, and a run with no shade. Jay's first 70.3 and the race that made the distance the point.",
    races: ["honu-70-3-2023"],
    offIsland: true,
  },
  {
    name: "Lanikai 8K",
    month: 7,
    when: "July",
    where: "Lanikai and Kailua",
    distance: "8K",
    discipline: "run",
    take: "A short loop in the most photographed neighborhood on the island. Short does not mean easy in July.",
    races: ["lanikai-8k-2023"],
  },
  {
    name: "Na Wahine & Kane Sprint Triathlon",
    month: 7,
    when: "July",
    where: "Oahu",
    distance: "Sprint",
    discipline: "tri",
    take: "A sprint is where you learn transitions without the day being ruined by them. We raced it the summer Jay's new bike arrived.",
    races: ["na-wahine-kane-sprint-2023"],
  },
  {
    name: "Norman Tamanaha 15K",
    month: 8,
    when: "August",
    where: "Honolulu",
    distance: "15K",
    discipline: "run",
    take: "First race of the Marathon Readiness Series. If you are doing the Honolulu Marathon, this is where the build gets a bib.",
    races: ["norman-tamanaha-15k-2023"],
    series: "Marathon Readiness Series 1 of 5",
  },
  {
    name: "Dick Evans Memorial Road Race",
    month: 8,
    when: "August",
    where: "Around Oahu",
    distance: "112 mi",
    discipline: "bike",
    take: "A full lap of the island. The same distance as an Ironman bike leg, in August, with real traffic. It taught us what 112 miles of fueling looks like.",
    races: ["dick-evans-112-2023"],
  },
  {
    name: "Runner's HI 20K",
    month: 9,
    when: "September",
    where: "Honolulu",
    distance: "20K",
    discipline: "run",
    take: "Second in the series. The distance steps up and so does the heat, because September is the hottest stretch of the year here.",
    races: ["runners-hi-20k-2023"],
    series: "Marathon Readiness Series 2 of 5",
  },
  {
    name: "Waikiki 2.4-mile swim",
    month: 9,
    when: "September",
    where: "Waikiki",
    distance: "2.4 mi",
    discipline: "swim",
    take: "The full Ironman swim distance, in the ocean, with no bike waiting. A good way to find out if the swim is the thing you should be worried about.",
    races: ["waikiki-2-4-mile-swim-2023"],
  },
  {
    name: "Honolulu Century Ride",
    month: 9,
    when: "Late September",
    where: "Kapiolani Park up the windward coast",
    distance: "25 to 100 mi",
    discipline: "bike",
    take: "Out and back along the windward side with distance options, so it fits any point in a season. The 100 is a long, hot, beautiful day.",
    races: ["honolulu-century-ride-2023"],
  },
  {
    name: "Hybrid Design 25K",
    month: 9,
    when: "Late September or early October",
    where: "Honolulu",
    distance: "25K",
    discipline: "run",
    take: "Third in the series. Past the half-marathon distance now, which is the point.",
    races: ["hybrid-design-25k-2023"],
    series: "Marathon Readiness Series 3 of 5",
  },
  {
    name: "Tantalus 10-Mile Challenge",
    month: 10,
    when: "October",
    where: "Tantalus and Round Top",
    distance: "10 mi",
    discipline: "run",
    take: "Up the mountain road above the city and back down. Not a PR course. A legs-and-honesty course.",
    races: ["tantalus-10-mile-2023"],
  },
  {
    name: "BOCA Hawaii 30K",
    month: 10,
    when: "October",
    where: "Honolulu",
    distance: "30K",
    discipline: "run",
    take: "Fourth in the series and the longest. 30K in October is the closest thing to a marathon dress rehearsal you will get with a bib on.",
    races: ["boca-hawaii-30k-2023"],
    series: "Marathon Readiness Series 4 of 5",
  },
  {
    name: "Val Nolasco Half Marathon",
    month: 11,
    when: "November",
    where: "Honolulu",
    distance: "13.1 mi",
    discipline: "run",
    take: "The last race in the series, a month out from the marathon. Run it as a check, not a race, if December is the goal.",
    races: ["val-nolasco-half-2023"],
    series: "Marathon Readiness Series 5 of 5",
  },
  {
    name: "Kaiwi Coast Fun Run",
    month: 11,
    when: "November",
    where: "Kaiwi coast, east Oahu",
    distance: "Short",
    discipline: "run",
    take: "The coastline between Sandy Beach and Makapuu. Fun run is the right name. Go for the view and the company.",
    races: ["kaiwi-coast-fun-run-2023"],
  },
  {
    name: "Turtle Bay Triathlon",
    month: 11,
    when: "November",
    where: "Turtle Bay, North Shore",
    distance: "Short course",
    discipline: "tri",
    take: "A late-season tri on the North Shore when the surf is already coming up. A good one to end a triathlon year on.",
    races: ["turtle-bay-triathlon-2023"],
  },
  {
    name: "Honolulu Marathon",
    month: 12,
    when: "Second Sunday of December",
    where: "Ala Moana to Kapiolani Park",
    distance: "26.2 mi",
    discipline: "run",
    take: "A 5 a.m. start, fireworks, Diamond Head twice, and no cutoff time. The reason the whole Oahu running calendar is shaped the way it is. Jay's 50th birthday race.",
    races: ["honolulu-marathon-for-fifty", "honolulu-marathon-2023"],
  },
];
